### ISSUE TITLE
Dictionary vs Record

### ISSUE THREAD

**Issue by brainkim** [krzkaczor/ts-essentials#1]
Thanks for publishing this! I’m wondering if there’s any difference between the `Dictionary` type you define and typescript's builtin `Record` type?

**Comment by krzkaczor** [comment]
@brainkim that's a good catch, someone already mentioned me that this is part of standard library. There's no difference. I will clarify that it in the readme.

**Comment by brainkim** [comment]
Good to know!

**Comment by krzkaczor** [comment]
Description fixed in `ts-essentials@1.0.1`.
