### ISSUE TITLE
Add OptionalRecord / OptionalDictionary

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#103]
https://stackoverflow.com/a/53276873/580181

**Comment by quezak** [comment]
Is it worth adding a separate type though? `Partial<Record<...>>` looks simple enough, unless you use it many times in many files

**Comment by Beraliv** [comment]
I also think it doesn't make sense to add as the complexity is minimal

**Comment by quezak** [comment]
Closing for now then.
