### ISSUE TITLE
Add Assert/Invariant type

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#106]
Utilizing TS3.7 assertion functions: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

```typescript
function assert(condition: any, msg?: string): asserts condition {
    if (!condition) {
        throw new Error(msg)
    }
}
```

It's very similar to [`invariant`](https://www.npmjs.com/package/invariant). 

Obviously it's not "type-only" but it utilizes advanced types (assertion functions), has minimal runtime footprint and is very useful on everyday use.

WDYT?

More examples:

```typescript
const something: string | undefined = "abc" as any
assert(something, "Something has to be defined!")
// from now on `something` is string

const anything: any = "abc" as any
assert(anything instanceof String, "anything has to be a string!")
// from now on `anything` is string
```

**Comment by quezak** [comment]
:cool:
