### ISSUE TITLE
Please make changelog

### ISSUE THREAD

**Issue by SQReder** [krzkaczor/ts-essentials#117]
Please provide a changelog, or publish it with release tags. We just see that major version number jumped from 3 to 4 but have no clue, what was changed.

**Comment by krzkaczor** [comment]
@SQReder yeah, sorry about that. I need to figure out a better way of managing new  releases. I am gonna write one now. Some summary is here: https://github.com/krzkaczor/ts-essentials/issues/107 
But the breaking change is that it requires TS 3.7 now.

**Comment by SQReder** [comment]
Thanks for the quick response! I think changelog notes in the release tab is a good place to deal with it.

**Comment by quezak** [comment]
Yeah, I think it's good to add the releases here on github, with some changelog and maybe PR links.

Some of my projects are even configured to actually do the release when a tag is added, and I just add a new release directly from github, which triggers a deployment on CI.

**Comment by krzkaczor** [comment]
Done: https://github.com/krzkaczor/ts-essentials/releases/tag/v4.0.0
