### ISSUE TITLE
DeepOmit changes optional fields to nullable?

### ISSUE THREAD

**Issue by VienNguyen113** [krzkaczor/ts-essentials#118]
- Example:
```

type Test = {
  id: string;
  age: number;
  name?: string
}
type OmittedTest = DeepOmit<Test, {age: never}>
```
<img width="338" alt="Screen Shot 2020-01-06 at 17 05 32" src="https://user-images.githubusercontent.com/11764707/71811242-c1105980-30a6-11ea-972f-b8458f5a8f40.png">

- My question is: why does the deepOmit turn optional fied `name?:string` to `name:string|undefined`

**Comment by quezak** [comment]
// please use meaningful issue titles, I've edited this one

It may be just how TS works -- an optional property essentially has the `X | undefined` type. We might have to handle optional things separately.

Side note: `Filter[K] extends true` [here](https://github.com/krzkaczor/ts-essentials/blob/master/lib/types.ts#L139) should probably be `Filter[K] extends never`, looks like a remainder from when we were still discussing how to implement `DeepOmit`. I'll check tomorrow when I get back to my computer.

**Comment by VienNguyen113** [comment]
thanks for editing the title, I don't think  ` an optional property essentially has the X | undefined type.` is right, `X|undefined` still require assigning the property

**Comment by VienNguyen113** [comment]
Here is code sanbox for a closer look. https://codesandbox.io/s/exciting-noether-s5hlp

**Comment by benallfree** [comment]
Came here with the same issue, this feels like DeepOmit is broken since whenever [optional properties](https://www.typescriptlang.org/docs/handbook/interfaces.html#optional-properties) came along.

**Comment by bbarry** [comment]
Here is a fix:

```typescript

type OptionalKeys<T> = {
  [K in keyof T]-?: undefined extends { [K2 in keyof T]: K2 }[K] ? K : never
}[keyof T];

type RequiredKeys<T> = Exclude<keyof T, OptionalKeys<T>>;
type MergeIntersection<T> = { [K in keyof T]: T[K] };

/** Recursively omit deep properties */
export type DeepOmit<T extends DeepOmitModify<Filter>, Filter> = T extends Builtin
  ? T
  : T extends Map<infer KeyType, infer ValueType>
  ? ValueType extends DeepOmitModify<Filter>
    ? Map<KeyType, DeepOmit<ValueType, Filter>>
    : T
  : T extends ReadonlyMap<infer KeyType, infer ValueType>
  ? ValueType extends DeepOmitModify<Filter>
    ? ReadonlyMap<KeyType, DeepOmit<ValueType, Filter>>
    : T
  : T extends WeakMap<infer KeyType, infer ValueType>
  ? ValueType extends DeepOmitModify<Filter>
    ? WeakMap<KeyType, DeepOmit<ValueType, Filter>>
    : T
  : T extends Set<infer ItemType>
  ? ItemType extends DeepOmitModify<Filter>
    ? Set<DeepOmit<ItemType, Filter>>
    : T
  : T extends ReadonlySet<infer ItemType>
  ? ItemType extends DeepOmitModify<Filter>
    ? ReadonlySet<DeepOmit<ItemType, Filter>>
    : T
  : T extends WeakSet<infer ItemType>
  ? ItemType extends DeepOmitModify<Filter>
    ? WeakSet<DeepOmit<ItemType, Filter>>
    : T
  : T extends Array<infer ItemType>
  ? ItemType extends DeepOmitModify<Filter>
    ? Array<DeepOmit<ItemType, Filter>>
    : T
  : T extends Promise<infer ItemType>
  ? ItemType extends DeepOmitModify<Filter>
    ? Promise<DeepOmit<ItemType, Filter>>
    : T
  : MergeIntersection<{ [K in Exclude<OptionalKeys<T>, keyof Filter>]+?: T[K] } &
      OmitProperties<
        {
          [K in Extract<OptionalKeys<T>, keyof Filter>]+?: Filter[K] extends true
            ? never
            : T[K] extends DeepOmitModify<Filter[K]>
            ? DeepOmit<T[K], Filter[K]>
            : T[K];
        },
        never
      > & { [K in Exclude<RequiredKeys<T>, keyof Filter>]: T[K] } &
      OmitProperties<
        {
          [K in Extract<RequiredKeys<T>, keyof Filter>]: Filter[K] extends true
            ? never
            : T[K] extends DeepOmitModify<Filter[K]>
            ? DeepOmit<T[K], Filter[K]>
            : T[K];
        },
        never
      >>;
```

It is probably not quite correct because it reorders the properties. Still this test passes:

```typescript
type Test = {
  id: string;
  age: number;
  name?: string
}
type DeepOmittedTest = DeepOmit<Test, { age: never }>;

type test = AssertTrue<IsExact<DeepOmittedTest, Expected>>;
```

**Comment by benallfree** [comment]
@bbarry Works great, thank you very much.

**Comment by quezak** [comment]
Thanks! Looks complicated, but after a deeper dive looks like it needs to be complicated to work correctly :smiley:

@bbarry could you prepare a PR with the fix?

The test type should also include a field that's not optional, but is nullable, to make sure future changes don't make it optional (`x: boolean | undefined` or something)

**Comment by bbarry** [comment]
I can try but it might be a while before I an make a PR that I have tested locally (I wrote that i the typescript playground). My internet just isn't good enough to use npm...
https://github.com/npm/cli/issues/1052

I sort of think that this is really a bug in typescript itself though. The syntax `{ [K iin ...]: ...}` is usually agnostic about changing the property's optional status(notice the MergeIntersection utility type).

**Comment by quezak** [comment]
> I sort of think that this is really a bug in typescript itself though. The syntax `{ [K iin ...]: ...}` is usually agnostic about changing the property's optional status(notice the MergeIntersection utility type).

Yeah, that sounds logical. @krzkaczor maybe we should file a bug to TS? :smile:
