### ISSUE TITLE
DeepRequired removes nullability

### ISSUE THREAD

**Issue by CS-Jfilmer** [krzkaczor/ts-essentials#120]
Problem: DeepRequired is forcing properties to be both "not undefined" AND "not null"

I'm not sure if this is intentional, but the behaviour is different to the native Required

	interface A {
		a?: string | null
		b?: B
	}
	interface B {
		b?: string | null
	}
	
	export const x: DeepRequired<A> = { a: null, b: {b: null} } // Errors as DeepRequired removes nullability
	
	export const y: Required<A> = {a: null, b: {}} // Does not error, as Required allows properties to be null but not undefined

I gave the original DeepRequired suggested [here](https://github.com/krzkaczor/ts-essentials/issues/2) a go and it seems to work as I'd expect

	type DeepRequired<T> = T extends any[]
		? DeepRequiredArray<T[number]>
		: T extends {}
		? {
				[K in keyof T]-?: DeepRequired<T[K]>
		  }
		: T
	interface DeepRequiredArray<T> extends Array<DeepRequired<T>> {}

**Comment by quezak** [comment]
I see that the current version of `DeepRequired` at the bottom type nodes uses `NonNullable<T>`, instead of plain `T` as the original. Is this by design @krzkaczor?

(I personally actually like the current version better, I don't like treating `null` and `undefined` differently, required is required :smiley: )

**Comment by CS-Jfilmer** [comment]
Personally I quite like using nullable so you can differentiate between the caller
"deliberately leaving something out" vs "just forgetting to include it".

Contrived example:

	interface CalculationOptions {
		decimalPlaces: number | null
		left: number
		right: number
	}
	
	function calculate(options: CalculationOptions) {
		return (options.left + options.right).toFixed(
			options.decimalPlaces === null ? 2 : options.decimalPlaces
		)
	}
	
	calculate({ left: 1, right: 2 }) // <---- error's as you've forgotten to have an explicit opinion on decimalPlaces
	calculate({ left: 1, right: 2, decimalPlaces: null }) // <---- you can still say you don't care about decimalPlaces, but you need to be deliberate

If I was literally programming this I'd probably just make decimalPlaces optional, but I use the general principle when constructing more complex types that sit in front of functionality that's called by foreign code (API's, libraries, etc) to aid the caller.

**Comment by quezak** [comment]
Yeah, I'd be happy with that if there also was no difference between _not passing a property_ and _explicitly passing an `undefined`_, but that's just how JS works...

I understand there are valid cases where you'd want `DeepRequired` to keep the nullable option, and you always could then do `DeepRequired<DeepNonNullable<T>>` to achieve the current behavior.

Keeping in line with how TS's `Required` works is also important, so our lib remains intuitive to use.

@krzkaczor what do you think?

The big questions is: when was this introduced and how many people depend on the current behavior? implying: if we change this, should it be a breaking change?

**Comment by lucifer1004** [comment]
When I first refactored the `Deep-*` types, the bottom type of `DeepRequired` is already `NonNullable`, so I remained this behavior all the time.

**Comment by glen-84** [comment]
It's quite unexpected that `DeepRequired` behaves differently to the built-in `Required` type, as mentioned by the OP.

`Required` is supposed to set the properties to non-optional (i.e. remove the `?`), not to change anything regarding the type.

With [strict optional properties](https://github.com/microsoft/TypeScript/pull/43947), even `undefined` would not be removed from the type.

**Comment by Beraliv** [comment]
> Yeah, I'd be happy with that if there also was no difference between not passing a property and explicitly passing an undefined, but that's just how JS works...

@quezak that's not true, you still have `in` operator to distinguish those things

<img width="150" alt="Screenshot 2021-08-15 at 16 11 55" src="https://user-images.githubusercontent.com/2991847/129481347-381506ff-a5f1-4c7a-996f-9afdeab5591e.png">

**Comment by Beraliv** [comment]
@krzkaczor do we want to change anything here? Look valid that we need to remove only `?`, but not `null` and `undefined` itself

**Comment by krzkaczor** [comment]
Yes, I agree that it seems like a current behavior is invalid. `DeepRequired` should behave similarly to builtin `Required`.

**Comment by Beraliv** [comment]
> Yes, I agree that it seems like a current behavior is invalid. `DeepRequired` should behave similarly to builtin `Required`.

So the plan here is:

- to cover current logic with tests
- to change the logic in patch version (which will be closer to `Required`)
- to release it under 8.0.1

**Comment by Beraliv** [comment]
Release in https://github.com/krzkaczor/ts-essentials/releases/tag/v8.1.0
