### ISSUE TITLE
Feature request: DeepNullable

### ISSUE THREAD

**Issue by FrancescoBorzi** [krzkaczor/ts-essentials#124]
What about implementing a `DeepNullable` type such that, given a `MyType` type:

```
interface MyType {
  field1: string;
  field2: string;
  field3: {
    field4: string;
    field5: number;
  };
}
```

the `DeepNullable<MyType>` would be equal to:

```
  field1: string | null;
  field2: string | null;
  field3: {
    field4: string | null;
    field5: number | null;
  };
```

this is different than `DeepPartial` as properties should never be undefined.

EDIT: also non-primitive properties should always be defined. So when you navigate through the object you should never get "unable to access XXX of undefined".

**Comment by quezak** [comment]
While I don't personally like using `null`, it could be useful for some DB tools, or people that do like it :) You're welcome to prepare a PR.

**Comment by krzkaczor** [comment]
As @quezak said, it seems to be useful. 

I encourage you to create a PR - it should be very similar to already existing types.

**Comment by FrancescoBorzi** [comment]
@krzkaczor @quezak can you please help with https://github.com/krzkaczor/ts-essentials/pull/125 ?
