### ISSUE TITLE
Add DeepWritable type

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#13]

**Comment by epeli** [comment]
Immer has good implementation of this if you need examples 

https://github.com/mweststrate/immer/blob/42b14bd4e2f343a947697a9dfdf210970be112f3/src/immer.d.ts#L26-L36

**Comment by krzkaczor** [comment]
@epeli oh, good to know, thanks!

**Comment by krzkaczor** [comment]
Released as `v2.0.3`.
