### ISSUE TITLE
DeepPartialOrNullable type?

### ISSUE THREAD

**Issue by s-edlund** [krzkaczor/ts-essentials#145]
I was looking for a type like this but wasn't able to find it. Perhaps I missed it? 

Anyway, it would turn all properties (nested deeply) to allow for `null | undefined`. I have need for a type like that in my project. Thanks!

**Comment by quezak** [comment]
does that work? :smiley: 
```typescript
type DeepPartialOrNullable<T> = DeepPartial<DeepNullable<T>>` 
```

**Comment by s-edlund** [comment]
Thanks, easy and exactly what I needed! My first attempt using `DeepPartial<T> | DeepNullable<T>` failed spectacularly. :)

**Comment by s-edlund** [comment]
Just a little more follow up on this. 

```
type DeepPartialOrNullable<T> = DeepPartial<DeepNullable<T>>
``` 

Did not work in my case, but:

```
type DeepPartialOrNullable<T> = DeepNullable<DeepPartial<T>>
```

did work. In the first case, this gives a compilation error:

```
export type DeepPartialOrNull<T> = DeepPartial<DeepNullable<T>>;

declare interface X {
    y: {[key:string] : Y}
}

declare interface Y {
    z: string;
}

const test : DeepPartialOrNull<X> = {
    y: {
        z: null
    }
}
```

error: `error TS2322: Type '{ z: null; }' is not assignable to type '{ [x: string]: { z?: string | null | undefined; } | undefined; }'.
  Property 'z' is incompatible with index signature.
    Type 'null' is not assignable to type '{ z?: string | null | undefined; } | undefined'.
`

Switching it around it compiles fine. Don't ask me why.

**Comment by quezak** [comment]
Probably some implementation detail, let's ignore this unless it causes problems later.
Glad you've worked this out, I'll close the issue for now :)

**Comment by krzkaczor** [comment]
Just as a side note: IMO using both `null` and `undefined` in your codebase is an antipattern. Pick one and stick to it (and probably it should be `undefined`).

**Comment by s-edlund** [comment]
Yes close for sure. The use case is using `deepmerge`` (https://www.npmjs.com/package/deepmerge). To delete a key when merging, we need to set the key value to `undefined`. But since what we're merging comes from serialized JSON, and JSON values cannot be `undefined` -- but they can be `null` -- we need the model to support both. thx
