### ISSUE TITLE
Add Tuple constraint

### ISSUE THREAD

**Issue by epeli** [krzkaczor/ts-essentials#15]
If I do 

```ts
function foo<T>(tuple: T): T {
    return tuple;
}

const ret = foo([1, "s"]);
```

The return type will be `(string | number)[]` instead of `[number, string]`

This can be fixed by using `[any] | any[]` constraint but this very cryptic and hard to remember.

So I propose a `Tuple` type to be added:

```ts
type Tuple = [any] | any[]
```

Usage 

```ts
function foo<T extends Tuple>(tuple: T): T {
    return tuple;
}
```

Background https://github.com/Microsoft/TypeScript/issues/29780

**Comment by Andarist** [comment]
This is... weird 😱Highly useful though!

**Comment by krzkaczor** [comment]
@epeli this seems to be useful 👍 I think it goes well with already existing [literal type](https://github.com/krzkaczor/ts-essentials#literal-types). 

It would be great if you could create a PR ;)
