### ISSUE TITLE
UnionToIntersection returns never in some cases for TS3.9.x

### ISSUE THREAD

**Issue by Oikio** [krzkaczor/ts-essentials#150]
```type T = UnionToIntersection<{ bar: 'one' } | { bar: 'two' }>```
Returns never in TS3.9.x, works in 3.8.x.

Looks like dark magic is not working anymore =(. I would really appreciate help with this one.

Or maybe it will make more sense to open ticket in Typescript project?

**Comment by bbarry** [comment]
But that intersection is never in 3.9:

```typescript
type T = { bar: 'one' } & { bar: 'two' };
```

See https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#intersections-reduced-by-discriminant-properties

**Comment by bbarry** [comment]
```typescript
type UnionType = { bar: 'one' | 'three' } | { bar: 'two' | 'three' };

type IntersectionType = UnionToIntersection<UnionType>;

const a:IntersectionType = { bar: 'three'};
```

results in:

```typescript
type IntersectionType = { bar: 'three' };
```

**Comment by papb** [comment]
Indeed, nice catch @bbarry!

**Comment by krzkaczor** [comment]
Okay, it seems like such an intersection should result in `never` and TS 3.9 fixed it. Thanks, @bbarry for figuring it our so quickly :) 

Example for `UnionToIntersection` type work as expected, so I am closing this one.

**Comment by Oikio** [comment]
Thank you! For anyone thinking how to overcome such case - one can use `DeepOmit` ts-essentials to remove intersected field.

**Comment by forivall** [comment]
For the use case where all options should be available, i use the following: https://gist.github.com/forivall/ddd9255b7bb47ce0a7a9b90747d9afdb

```ts
import type { UnionToIntersection } from 'ts-essentials';

export type UnionToInterface<T> = {
  [K in Extract<keyof UnionToIntersection<T>, keyof T>]: T[K];
} &
  {
    [K in Exclude<keyof UnionToIntersection<T>, keyof T>]?: T extends {
      [_ in K]: infer U;
    }
      ? U
      : never;
  };
```
