### ISSUE TITLE
Suggestion: Optional keys / Required keys

### ISSUE THREAD

**Issue by bbarry** [krzkaczor/ts-essentials#154]
### OptionalKeys

Gets keys of an object which are optional.

```typescript
type T = {
  a: number;
  b?: string;
  c: string;
  d?: string;
};
type Result = OptionalKeys<T>;
// Result:
// "b" | "d"
```

### RequiredKeys

Gets keys of an object which are required.

```typescript
type T = {
  a: number;
  b?: string;
  c: string;
  d?: string;
};
type Result = OptionalKeys<T>;
// Result:
// "a" | "c"
```

---

These utility types are necessary for DeepOmit and are included in #153

**Comment by krzkaczor** [comment]
Fixed by https://github.com/krzkaczor/ts-essentials/pull/153
