### ISSUE TITLE
ExactPartial

### ISSUE THREAD

**Issue by xenoterracide** [krzkaczor/ts-essentials#156]
I have this code
```ts
        drinks.push(await naf.drink(await naf.order({ kiosk })));
```
drink has this signature
```ts
  async drink(part: Partial<DrinkEntity> = {}): Promise<DrinkEntity> {
```

problem is, I was able to pass an entity completely unrelated to `DrinkEntity`

I want it so that it only has keys that are in the Partial, or no keys at all, if it has any keys that aren't in the partial it shouldn't compile.

**Comment by quezak** [comment]
@xenoterracide can you show a complete minimal example of what you're describing? `Partial<T>` should already accept only keys from `T`.

**Comment by xenoterracide** [comment]
https://stackoverflow.com/q/62207479/206466

**Comment by xenoterracide** [comment]
`Partial<DrinkEntity>` was excepting an `OrderEntity` and that does not have a 100% matching signature.

Opaque, might be a decent answer, but I had the same problem with the Opaque provided in `ts-essentials` as I described here.

> had a problem with mymethod, accessing the properties inside of the method were resulting in a compiletime failure.

the Opaque from `ts-fest` seems to work, and doesn't require me to also pass a string, but the silly `as` is still required...

**Comment by quezak** [comment]
Ok, you're right, `Partial<T>` forbids non-T keys only for literal objects -- makes sense with the explanation you linked: in other cases you can pass e.g. a subclass instance that has more properties.

```
interface Foo { a: string; b: string }
// Correctly doesn't compile
const test1: Partial<Foo> = { a: 'a', d: 'd' };
const bar = { a: 'a', d: 'd' };
// Passes
const test2: Partial<Foo> = bar;
```

On a first look though, it doesn't look like this is possible to be solved with just a type, only with a generic method, like mentioned in the `UPDATE` section of the [answer](https://stackoverflow.com/a/62207847/1815209) to your SO question.

**Comment by xenoterracide** [comment]
yeah... I'm going to add my own answer to use Opaque... but like I said, Opaque on here... has ... issues... I can open a new bug for that, if you want?

**Comment by quezak** [comment]
Opaque types, at least how they can be done in TS, are intended to be used with explicit casts here and there. But yeah, if you have some problems with them, you can post a new issue (and tag @krzkaczor since he's the author of those)

**Comment by Beraliv** [comment]
I think we cannot do anything here

I will close the issue, but if you find a bug, please create a related issue
