### ISSUE TITLE
Wrong usage of `Opaque` type in example

### ISSUE THREAD

**Issue by chjdev** [krzkaczor/ts-essentials#158]
The `Opaque` type is declared as:

```ts
export declare type Opaque<K, T> = T & {
    __TYPE__: K;
};
```

however in the example it is used like:

```ts
type PositiveNumber = Opaque<number, "positive-number">;
```

which leads to values declared as `PositiveNumber` being treated like strings.
Shouldn't this be the other way around?

```ts
type PositiveNumber = Opaque<"positive-number", number>;
```

This way prevents the assignability but keeps treating them like numbers.

**Comment by krzkaczor** [comment]
Ohh, you might be right... I feel like it should be the other way around. I guess my dyslexia kicked in when I wrote it. I feel like we should do a breaking change and change the order of these parameters. The problem is that it can be hard to spot while migrating...

```typescript
export declare type Opaque<T, K> = T & {
    __TYPE__: K;
};
```

**Comment by chjdev** [comment]
As you mentioned in the other issue, I agree it's more intuitive to have the type first. Not a big fan of breaking changes but I guess since the documentation was different from the start it might be warranted.

Maybe there's a fix possible, I cooked up the following which seems to work and accept both parameter orders.
```ts
export declare type Opaque<T, K> = K extends string
  ? T extends string
    ? string & {
        __TYPE__: K & T;
      }
    : T & {
        __TYPE__: K;
      }
  : T extends string
  ? K & {
      __TYPE__: T;
    }
  : never;
```

Basically it checks whether both `T` and `K` are strings and if so uses the intersection `T & K` as the tag, which will have the stricter bound of the string enum. If `T` and `K` are different and one of them is a string, it uses the string as tag. If neither is a string then it's a `never`.

```ts
let a: Opaque<string, "hello"> = "hello";
const b: Opaque<"hello", string> = "hello";
a = b;

let d: Opaque<number, "a"> = 3;
const e: Opaque<"a", number> = 3;
d = e;
```

<img width="611" alt="image" src="https://user-images.githubusercontent.com/973941/84590861-48be7900-ae3a-11ea-98d9-777cd0646245.png">

Am I missing a corner case?

**Comment by krzkaczor** [comment]
@chjdev thanks for this! I don't think that supporting both ways is something that we should care about... This would create lots of confusion I think.

I wanted to rather enforce the second argument to be a literal type, something like https://stackoverflow.com/a/60185654/580181

**Comment by chjdev** [comment]
The SubString type in the link looks quite useful, and enforcing the second argument to be a literal  is a good idea I think

**Comment by krzkaczor** [comment]
@all-contributors please add @chjdev for idea

**Comment by krzkaczor** [comment]
Done in version 7.
