### ISSUE TITLE
Make the Opaque "string" optional

### ISSUE THREAD

**Issue by xenoterracide** [krzkaczor/ts-essentials#159]
doesn't have to be an exact copy https://github.com/sindresorhus/type-fest/blob/HEAD/source/opaque.d.ts

I'd just like to be able to write

`Opaque<Partial<MyFoo>>`

also see #158, I had problems using Opaque from here because of this.

I get this would be an API breaking change, maybe a new "type" could be introduced, or a new major version, either way I'm using fest for this right now.

**Comment by krzkaczor** [comment]
Uhh I am really not sure if this is the right API design. By omitting the second argument these two types would be the same:

```typescript
type PosNumber = Opaque<number>
type NegNumber = Opaque<number>
```

Which defeats the whole purpose of using opaque types in the first place... I think that you should simply roll with rewriting your code to:

```
Opaque<Partial<MyFoo>, "Partial-MyFOO">
```

Only then you are certain that that you won't be able to mismatch types. 

I am closing this for now but let me know WDYT.

**Comment by xenoterracide** [comment]
I think you have the implementation of `Opaque` backwards, the string comes first. Other than that, meh.

**Comment by krzkaczor** [comment]
Yeah this opaque type **should** be the other way around... https://github.com/krzkaczor/ts-essentials/issues/158

I noticed it while working with it in the past, that it's much more intuitive to do first type and literal string later. Anyway, I am considering doing a breaking change here.
