### ISSUE TITLE
Issue with generics and DeepPartial, worked in 2.x

### ISSUE THREAD

**Issue by Dragory** [krzkaczor/ts-essentials#161]
The following example worked in ts-essentials@2 but throws an error in `6.0.7` (haven't tested other versions yet):

```ts
interface PartialFoo<T> {
  config: DeepPartial<T>;
}

interface Foo<T> extends PartialFoo<T> {
  config: T;
}
```

The error:
```
Interface 'Foo<T>' incorrectly extends interface 'PartialFoo<T>'.
  Types of property 'config' are incompatible.
    Type 'T' is not assignable to type 'DeepPartial<T>'.
```

Surely `T` should be assignable to `DeepPartial<T>`?

`ts-essentials` version `6.0.7`, TypeScript version `3.9.5`.

**Comment by kmdrGroch** [comment]
@Dragory previously (in @2) it was available since you had to use object as a base T:
```ts
type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Primitive
    ? T[P]
    : T[P] extends Function
    ? T[P]
    : T[P] extends Date
    ? T[P]
    : T[P] extends Array<infer U>
    ? Array<DeepPartial2<U>>
    : T[P] extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial2<U>>
    : DeepPartial2<T[P]>;
};
```

Now since `T` can be basically `any`, you can't ensure T and DeepPartial<T> will be the same. The basic example I guess will be using `Set` / `Map` as a base type to `DeepPartial`

**Comment by Beraliv** [comment]
I think we can do nothing here

I will close it for now
