### ISSUE TITLE
DeepOmit makes everything optional

### ISSUE THREAD

**Issue by cyberbiont** [krzkaczor/ts-essentials#167]
I presume that this is not the intended behaviour?
![изображение](https://user-images.githubusercontent.com/59398323/86138479-35c4cd80-baf7-11ea-93c9-6c183b5fdeba.png)

**Comment by quezak** [comment]
@cyberbiont which version are you on? We recently had some fixed about this.

**Comment by bbarry** [comment]
And what TS version?

locally trying this with latest of both I get this type output:

```typescript
type OmittedInCfgResult = {} & Pick<{}, never> & {
    b: number;
    c: number;
} & Pick<{
    a: never;
    d: {} & Pick<{}, never> & {
        bar: string;
    } & Pick<{
        foo: never;
    }, never>;
}, "d">
```

**Comment by cyberbiont** [comment]
Mistery solved 
The ts file I was testing this in was outside my `src` directory, which contains my main `tsconfig` fie (I use project references')
I move it there and now it works as it should.
Don't know what why exactly it matters, but it does.

**Comment by krzkaczor** [comment]
Thanks for figuring it out guys.
