### ISSUE TITLE
Suggestion: DeepNever and Subtract

### ISSUE THREAD

**Issue by cyberbiont** [krzkaczor/ts-essentials#168]
A little proposal here.

My use case is to make two complementary types by splitting one common type in two..

For this, I specify a subset of properties of type Common as a new type A, then I obtain type B by DeepOmit'ting properties of type A from type Common (for this, I need to convert all properties of type A to never first, for which I need DeepNever<A> type) . Then I have type A and type B that are complementary and add up to make type Common.

I believe this can be combined in one utility type, for example 
```ts
type Subtract<Common, A> = DeepOmit<Common, DeepNever<A>>
```

DeepNever and Subtract might useful types to add to collection

**Comment by quezak** [comment]
Looks fine to me, @krzkaczor opinions?

**Comment by cyberbiont** [comment]
Now that I think of it I guess it would be be even better to implement DeepPick type, the opposite of DeepOmit. It would take the same configuration format (i.e. a type with a set of properties set to 'never')  and then return a type made from this properties, taken from the Common type.

Something like

```
type Common = {
  a: number
  b: number
  c: {
   foo: string
   bar: string
  }
}

type Properties = {
  a: never,
  c: {
   foo: never
  }
}

type PartA = DeepPick<Common, Properties> // {a: number, c: {foo: string }
type PartB = DeepOmit<Common, Properties> // {b: number, c: {bar: string}

And in this way we would split Common type in two parts and get two complementary types.
>

**Comment by quezak** [comment]
great, this looks even better!

**Comment by quezak** [comment]
you can prepare a PR if you want.

**Comment by ifeltsweet** [comment]
I really want DeepPick for a typesafe selection of properties from my models. My use case is when selecting a subset of properties from MongoDB documents.

I'm trying to understand how DeepOmit works and maybe I can somehow negate it achieve DeepPick but my TypeScript skills are nowhere near that yet. I'd appreciate any suggestions!

**Comment by Beraliv** [comment]
Plan to release it tomorrow or the day after tomorrow in 8.1.0 🚀

**Comment by Beraliv** [comment]
Final changes are merged – https://github.com/krzkaczor/ts-essentials/pull/224

Will plan to release it soon-ish

**Comment by Beraliv** [comment]
Sorry, had problems with CI, release under https://github.com/krzkaczor/ts-essentials/pull/280
