### ISSUE TITLE
Strange scenario with DeepReadonly array fields

### ISSUE THREAD

**Issue by MichaelTontchev** [krzkaczor/ts-essentials#17]
I have the following minimal repro for a compile-time error:

```
interface IThing extends DeepReadonly<{
	field: string[];
}> {}

const a: DeepReadonly<IThing> = {
	field: ['lala'],
};

let b: IThing = {
	field: ['lala'],
};

b = a;
```

The last line there gives me the following error:

>[ts]
>Type 'DeepReadonlyObject\<IThing>' is not assignable to type 'IThing'.
>  Types of property 'field' are incompatible.
>    Property '[Symbol.iterator]' is missing in type 'DeepReadonlyObject<DeepReadonlyArray\<string>>' but required in type 'DeepReadonlyArray\<string>'. [2322]
>lib.es2015.iterable.d.ts(88, 5): '[Symbol.iterator]' is declared here.

If I change the definition of IThing to have `field` be explicitly DeepReadonly<string[]>, the error goes away. However, this is an ugly solution.

The question about where I might encounter such a scenario is not relevant, but for completeness, it's when I have a cache of objects stored in a DeepReadonly<Dictionary\<IThing>>, and I try to set one of the objects in this cache as the value on a field typed IThing.

Edit: Actually, my proposed workaround above seems to cause other downstream type issues...

**Comment by MichaelTontchev** [comment]
Hmm, this seems to stem from the fact that a ReadonlyArray in TS does not match any[].

Try the following:

```
interface ISome {
	readonly arr: string[];
	arr2: ReadonlyArray<string>;
}

type IsArrayWithReadonlyModifierAnArray = ISome['arr'] extends any[] ? true : false;
type IsReadonlyArrayAnArray = ISome['arr2'] extends any[] ? true : false;
```
IsArrayWithReadonlyModifierAnArray comes out to true.
IsReadonlyArrayAnArray comes out to false.

:( Any workaround?

**Comment by MichaelTontchev** [comment]
Seems that the following fixes things?

`export declare type DeepReadonly<T> = T extends Primitive ? T : **T extends (any[] | ReadonlyArray<any>) ? DeepReadonlyArray<T[number]>** : T extends Function ? T : DeepReadonlyObject<T>;`

That is, when checking T against any[], also check against ReadonlyArray<any>.

Does this seem right to you? Should I submit a PR?

**Comment by krzkaczor** [comment]
@MichaelTontchev nice findings. Could you create a PR? I will take a closer look at the weekend. Not sure now what's the proper solution.

**Comment by MichaelTontchev** [comment]
Fixed with the linked PR. Closing.
