### ISSUE TITLE
Suggest adding ts-essentials as a runtime dependency

### ISSUE THREAD

**Issue by mattleff** [krzkaczor/ts-essentials#172]
First off, thanks for a very useful library! 💎 

I've been using `ts-essentials` for a month now and slowly finding more and more types to utilize in my app. One I recently added was `UnreachableCaseError` for exhaustive switch case checking. Even though TS knows that `UnreachableCaseError` will never (aka `never`) be thrown, `UnreachableCaseError` is still referenced in the [runtime code `tsc` produces](https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAYwDYEMDOa4FUB2VgoIAWKARksAMLrACiUU0coMwOAJpvY1HAN4BYAFBxEEHGhhQArghjQAFADcUSacABccHMCXAoASn7DRotNLD6FAA1z5CJcsEQ0tAEj4q1wAL7WDANwmcD7CoULCMACelnAAItIAtolRAPJgMACW4pgAvHAA5BCWOAVwAD6FyBBowOxllQXSOADWOBAA7qVBEUIAZs1y2ThwhDCpOAnJaRnDaArFWTlaUynpSxIGWpJQmTgA5sYicGgdmTDEcAuzOUaCx6IINHAARMVsLxrBpnD4MNJQEYvc4FTDvHAAQhePR+T1qr2qtXYn2+pj+AKBIMwiLq0NRcOcL2abU6OBRDzRwH+gNemTgJD02ggcEy7AIeIpbL6KGkSBgXwpogA9EKWX04FEINI4B0pUh2KN2AqUO0YER9HBFsM4PJ4kk1jcJAAaCVSgpIJBwfZU5gMJjq-AQ1GiNWMDraYDuuwEYhkCjUWrcRRa24wkJhIA). Because I added `ts-essentials` in my `devDependencies` `UnreachableCaseError` wasn't available in my production environment when my server attempted to load modules.

Would it be worth mentioning in the [readme installation instructions](https://github.com/krzkaczor/ts-essentials/blob/master/README.md#install) that you may need to add `ts-essentials` in your `dependencies` if you are going to use any [functions](https://github.com/krzkaczor/ts-essentials/blob/master/lib/functions.ts)? It would have saved me a bit of debugging to figure out why my server went down. 😄 Thanks for your consideration!

**Comment by quezak** [comment]
Sure, you can submit a PR if you want :)
(also, kudos for a well prepared issue!)
