### ISSUE TITLE
Type that adds a property

### ISSUE THREAD

**Issue by mightyiam** [krzkaczor/ts-essentials#177]
Would this type be welcome?

Similar to `Merge`, but for a single property.

Not certain regarding the name.

```ts
export type Add<T, V, N extends string | symbol> = T & { [P in N]: V }
```

@gomain

**Comment by quezak** [comment]
@mightyiam is there a difference why you can't use `Merge` directly?

// also, you say "for a single property" but your example can add multiple properties, was this intended? For example `Add<{}, number, 'a' | 'b' | 'c'>` or even `Add<{}, number, string>`

**Comment by gomain** [comment]
It's for a usecase where N is inferred from a value
```ts
const AddProperty = <T, V, N extends string>(object: T, value: V, name: N): Add<T,V,N> = {
  return {
    ..object,
    [name]: value
  }
}
```

**Comment by quezak** [comment]
You could still write the above example's return type as `Merge<T, { [k in N]: V }>`.

@krzkaczor what do you think, is it worth sucha a "convenience alias"? I'm not 100% sure, because this really is just a different way to call `Merge` in a specific case where all the new properties have the same type. But also I'm not against it :smiley: though I'd reorder the args to `<T, KeyT, ValueT>` since it's more intuitive

**Comment by mightyiam** [comment]
It's meant for a single property. Does anyone happen to know how that could be implemented?

**Comment by quezak** [comment]
> It's meant for a single property. Does anyone happen to know how that could be implemented?

Exactly the same, only with some more complex requirements on what N can be (in particular that it can't have multiple values, for example using #100). But I don't think that's a problem, since your proposal actually works correctly when `N` / `KeyT` includes multiple properties.

**Comment by papb** [comment]
Hello, I think the following would give a better intellisense when hovering on VSCode:

```ts
export type Add<T, V, N extends string | symbol> = { [P in keyof T | N]: P extends N ? T[P] & V : T[P] }
```

**Comment by gomain** [comment]
> Hello, I think the following would give a better intellisense when hovering on VSCode:
> 
> ```ts
> export type Add<T, V, N extends string | symbol> = { [P in keyof T | N]: P extends N ? T[P] & V : T[P] }
> ```

 Shouldn't it be
```ts
type Add<T, V, N extends string | symbol> = { [P in keyof T | N]: P extends N ? V : T[P] }
```

**Comment by papb** [comment]
@gomain The type proposed by OP was

```
type Add<T, V, N extends string | symbol> = T & { [P in N]: V }
```

Therefore to be equivalent, it should be the way I proposed it.

**Comment by krzkaczor** [comment]
Thanks for the proposal but I think it's better to keep API smaller with only `Merge` type. We are already having problems with the number of types in this lib.
