### ISSUE TITLE
Suggestion: A generic type checker by member using type guards

### ISSUE THREAD

**Issue by fermmm** [krzkaczor/ts-essentials#179]
I always have to include this utility in all my projects, would be nice if ts-essentials have it:

```
/**
 * Check if an object is of type T by looking for a member inside of it.
 *
 * @param obj The object to check
 * @param memberName: The name of the member the object needs to have in order to be considered of type T
 */
function checkTypeByMember<T>(obj: any,  memberName:  keyof T): obj is T {
    return memberName in obj;
}
```

If you want this into the repo I can make a PR

You can try it here:
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyxyIcAthAFzIZhSgDmA3AQL4EGiSyIoDCcKPiIkEWADZYoNOgxAt2nGAFcQCMMBzIEACwgIA1gBUAngAcIAIVMBZCOQBG0ADzGAfAAosjgFY04EFMAGmRKJ2gAOQpqZEMIUywYZGMAShofX2RgDBSREmQoCDAVKFxw5yhoymzcTNYOAlV1TW1zeTBvPxp0KGxcAB9kQSh05AA3LGAAE3ySYBhPPQMTC2s7B0qXXv6vTNCAIjJKA9TUuYLicRBsCQgAOilGLt9744hU1gK2ZAgJDBQhEuBWutweTxe93EUlGXxIHEa7W4njw7xoBwAYtADmxPkA

**Comment by krzkaczor** [comment]
Thanks for this suggestion @fermmm! I think we'll pass, this works well only for types that can be checked by inspecting a single property. Other than that we try to avoid functions that have runtime impact. 

Again, thanks for suggesting this type!
