### ISSUE TITLE
"Writable" example is weird

### ISSUE THREAD

**Issue by bolatovumar** [krzkaczor/ts-essentials#191]
I'm trying the example provided for the `Writable` type as it is shown here: https://github.com/krzkaczor/ts-essentials/blob/master/README.md#Writable.

This is what I see in VSCode:
![Screen Shot 2021-02-27 at 2 21 00 PM](https://user-images.githubusercontent.com/1934678/109402028-50aa4480-7907-11eb-89ed-cc1dd39facc5.png)

If I re-write it like this then it's fine:

```ts
import type { Writable } from 'ts-essentials';

type Foo = {
  readonly a: number;
  readonly b: string;
};

const foo: Foo = { a: 1, b: 'b' };
(foo as Writable<typeof foo>).a = 42;
```

Is the example written this way intentionally?

**Comment by quezak** [comment]
Looks like the semicolon and newline was lost by mistake, thanks for reporting!
