### ISSUE TITLE
Suggestion: Override<T, R>

### ISSUE THREAD

**Issue by ryall** [krzkaczor/ts-essentials#193]
I noticed there's no simple override generic available in the standard library or in TS Essentials. 

It would be useful for modifying a few keys of a type as using the union operator simply adds more types and doesn't replace the original type.

```ts
type Override<T, R> = Omit<T, keyof R> & R;

interface Config {
  name: string;
  tags: string[] | () => string[];
}

type NormalizedConfig = Override<Config, {
  tags: string[];
}>;

// NormalizedConfig = { name: string; tags: string[] }
```

**Comment by papb** [comment]
There is: [Merge](https://github.com/krzkaczor/ts-essentials#merge)

**Comment by krzkaczor** [comment]
I think it's the same as merge.

**Comment by ryall** [comment]
Oh great! I thought I had tried that but must have been a confused by something. Thanks!
