### ISSUE TITLE
RequiredKeys generates never

### ISSUE THREAD

**Issue by fterradev** [krzkaczor/ts-essentials#196]
```
interface Test {
  opt?: string,
  req1: string,
  req2: string,
}

const key: RequiredKeys<Test> = 'req1';
```
Should have no errors.
But generates the error:
Type 'string' is not assignable to type 'never'.ts(2322)

The type `RequiredKeys<Test>` should return `"req1" | "req2"`. But instead generates `never`.

**Comment by quezak** [comment]
@fterradev it works for me, what are your typescript & ts-essential versions? Are you able to reproduce the issue on a clean directory?
![image](https://user-images.githubusercontent.com/666206/123673802-2dee5500-d841-11eb-9a34-7f056c78e4d9.png)

**Comment by Beraliv** [comment]
TS@4.3.4 with latest ts-essentials doesn't have the problem

Playground – https://tsplay.dev/WKkGgW

**Comment by fterradev** [comment]
It seems like ts-essentials requires Typescript's stricNullChecks.
So disabling `strictNullChecks` in TS Config (or having no tsconfig.json at all) is the condition for reproducing this error.
Playgroung: https://tsplay.dev/WGnKMm

**Comment by fterradev** [comment]
I guess now it's a matter of defining if it should either work even without `strictNullChecks`, or just have it documented in the README that this library requires `strictNullChecks` enabled.
If the latter is preferred, than maybe it is also possible to make the library generate a custom, more helpful error whenever it is imported/required saying something like:

ERROR: ts-essentials requires `strictNullChecks` enabled on tsconfig.

I really don't know if that's possible.

**Comment by Beraliv** [comment]
@krzkaczor what do you think if we mention that we prefer `strict` in tsconfig.json, or something less strict?

**Comment by krzkaczor** [comment]
@Beraliv yes i think adding a readme note that project should be used in strict mode is a good idea 👍
