### ISSUE TITLE
Explain what is this in readme

### ISSUE THREAD

**Issue by vitonsky** [krzkaczor/ts-essentials#199]
I don't know about this project and how it work, i ended up in this repository and want read about it.

Make in readme a one section with explain what is this.

Is this just TS library with types or this is an extension for TS compiler?

Write about it in top of readme, to any programmer can understand what your program about.

Let's make software descriptions more detail

**Comment by krzkaczor** [comment]
Hey @vitonsky!

Personally, I feel like "All essential TypeScript types in one place 🤙" is quite clear. It indicates that this is a set of *types*. If you want to propose a cleaner headline we can add another one below.

**Comment by vitonsky** [comment]
I bad know english language, so i will hard to formulate it anyway, and also i don't know what this project is.

My point about that you should explait what your project is, to every can understand this.

This short description "All essential TypeScript types in one place :call_me_hand:" is ok, but i speak not about it, but for example about write in section "What's inside?" something like "It's collection of TS types which can use to make your code more strict". This will enough to understand what about this project and how it work.

For example, i seen this project in twitter, google it and don't understand how it work until not seen explanation about adding utility property for type. I did think that it is extension for TS compiller with magic and i decide leave feedback to improve description, because main purpose of readme file is explain what is this, how it work and how it use and i think that we must write it clear

**Comment by krzkaczor** [comment]
Thanks for your comments. 

WDYT? https://github.com/krzkaczor/ts-essentials/pull/207/files

**Comment by vitonsky** [comment]
Yes, now better. Thank you

**Comment by krzkaczor** [comment]
@all-contributors please add @vitonsky docs

**Comment by krzkaczor** [comment]
@all-contributors please add @vitonsky for docs
