### ISSUE TITLE
Can merge be used with an array of N types to be merged?

### ISSUE THREAD

**Issue by jisaacks** [krzkaczor/ts-essentials#209]
If I have an array like:

```ts
const rules = [
    {} as { foo: 1 | 2 | 3},
    {} as { bar: 4 | 5 | 6},
]
```

I basically want to do:

```ts
type Rules = Merge<typeof rules[0], typeof rules[1]>
```

In order to get:

```ts
type Rules = {
  foo?: 1 | 2 | 3
  bar?: 4 | 5 | 6
}
```

But for N rules in the array.

Is this possible?

**Comment by Beraliv** [comment]
You can use playground to do that – https://tsplay.dev/Wv8AMN

Implementation looks like:

```ts
type _MergeN<T extends readonly any[], Result> = T extends readonly [infer Head, ...infer Tail]
  ? _MergeN<Tail, Merge<Result, Head>>
  : Result;
```

@krzkaczor do you think we can include it in implementation?

**Comment by krzkaczor** [comment]
@Beraliv sure! looks useful.

**Comment by Beraliv** [comment]
This might lead to update TypeScript version >=4.0.0

**Comment by Beraliv** [comment]
@jisaacks  The release version will be available soon, I'll let you know once it's available

**Comment by Beraliv** [comment]
Released in https://github.com/krzkaczor/ts-essentials/releases/tag/v8.0.0
