### ISSUE TITLE
Add Mutable type

### ISSUE THREAD

**Issue by yxliang01** [krzkaczor/ts-essentials#22]
`type Mutable<T>` is just the reverse of `type Readonly`. Although this might sound weird to have, this is convenient to have when dealing with incorrectly typed third-party library that even their API doesn't modify the input array, they still require a mutable array as argument. To conveniently continue use them, type assertion is needed. `Mutable<T>` can create the required type automatically without manually converting `Readonly` type to the mutable type case by case.

**Comment by krzkaczor** [comment]
Have you seen [Writable type](
https://github.com/krzkaczor/ts-essentials#writable)?

**Comment by yxliang01** [comment]
Oops. @krzkaczor I have read through the README before, but for some reason I didn't realize this is essentially the `Mutable` type I am thinking. Closing.

**Comment by yxliang01** [comment]
Err, no, after thinking a bit, although I didn't notice `Writable` but I was actually thinking of something more general. Like also converting from `ReadonlyArray` to `Array`.

**Comment by krzkaczor** [comment]
Thanks for your PR. Okay I think what's you're asking id DeepWritable type. https://github.com/krzkaczor/ts-essentials/issues/13 

I will try to implement it today.

**Comment by krzkaczor** [comment]
Released as `v2.0.3`. Please give it a try! ;)

**Comment by yxliang01** [comment]
Great! Thanks @krzkaczor  :)
