### ISSUE TITLE
`isExact` runtime function

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#222]
We already feature `Exact` type (releated: https://github.com/krzkaczor/ts-essentials/issues/87), but it's hard to use. Basically, it's only useful in function signatures. I propose a runtime function `isExact` that makes it easier to use this type:

```typescript
export type Exact<T, SHAPE> = T extends SHAPE ? (Exclude<keyof T, keyof SHAPE> extends never ? T : never) : never; // already in ts-essentials


function isExact<T, SHAPE>(x: Exact<T, SHAPE>): SHAPE {
  return x
}

type ABC = { a: number; b: number; c: number }
type C = { c: number }

const obj: ABC = {
  a: 1, b: 2, c: 3
}

const obj2= {
  c: 3
}

isExact<typeof obj, C>(obj) // error 
isExact<typeof obj2, C>(obj2) // fine
```

note the ABC extends C. With `isExact` we can prevent passing anything other than exactly type C.

Open questions:
1. Is it possible to drop `T` (`typeof obj`) thing?
2. What should be a runtime behaviour?

**Comment by Beraliv** [comment]
Would be good to have something like this: https://tsplay.dev/mx5x1W

```ts
const isExact = (<T extends unknown>() => <U extends unknown>(x: U): Exact<T, U> => {
  return x as Exact<T, U>;
})();
```

No need to specify useless `<T>` all the time and call it instead:

```ts

declare const abc: ABC;
declare const bc: BC;
declare const c: C;

isExact<ABC>(abc);
// @ts-expect-error
isExact<ABC>(bc);
// @ts-expect-error
isExact<ABC>(c);
```

But it's not working correctly for all the cases at the moment

**Comment by Beraliv** [comment]
But it's also working if we inline object – https://tsplay.dev/wQK0Gm 👀

**Comment by Beraliv** [comment]
Also, possible to solve it this way:

```ts
export type Exact2<T, U> = T extends U ? U extends T ? T : never : never;
```

Should work fine for shallow cases, but need to have a closer look for deep comparison

**Comment by Beraliv** [comment]
Also, might be good to have identity-like function:

```ts
function isExact<T>(x: T): T {
  return x
}
```

**Comment by Beraliv** [comment]
> Would be good to have something like this: https://tsplay.dev/mx5x1W
> 
> ```ts
> const isExact = (<T extends unknown>() => <U extends unknown>(x: U): Exact<T, U> => {
>   return x as Exact<T, U>;
> })();
> ```
> 
> No need to specify useless `<T>` all the time and call it instead:
> 
> ```ts
> declare const abc: ABC;
> declare const bc: BC;
> declare const c: C;
> 
> isExact<ABC>(abc);
> // @ts-expect-error
> isExact<ABC>(bc);
> // @ts-expect-error
> isExact<ABC>(c);
> ```
> 
> But it's not working correctly for all the cases at the moment

Final solution is similar:

```ts
const isExact = <ExpectedShape>() => <ActualShape>(x: Exact<ExpectedShape, ActualShape>): ExpectedShape => {
  return x;
};
```
