### ISSUE TITLE
Why is functions (assert) needed?

### ISSUE THREAD

**Issue by jjangga0214** [krzkaczor/ts-essentials#223]
Hi!

Thanks for the package!

I am curious what is the point of using [function(s)](https://github.com/krzkaczor/ts-essentials/blob/master/lib/functions.ts).

In case of assert (as there is only one function in function"s".ts, currently), nodejs already provides `assert`, and though the function behaves a little differently, it's fundamentally equivalent, and type is supported by `@types/node`.

So, why does the package export the function?

Thanks.

**Comment by Beraliv** [comment]
@jjangga0214 hey!

Thank you for the question!

`assert` is helpful if you don't have node environment (e.g. in any browser)
also, you cannot express `asserts condition` with types only (so it has its benefit)

`UnreachableCaseError` can be implemented differently (also you can have only a function) but the idea is still the same (check that you don't have more cases)

`noop` is just emptiness regarding the function which also cannot be implemented on the type level only

**Comment by Beraliv** [comment]
Let me know if you have more questions

I will close it for now
