### ISSUE TITLE
IsUnknown, IsNever and IsAny

### ISSUE THREAD

**Issue by Beraliv** [krzkaczor/ts-essentials#241]
Regarding `IsAny` I have a feeling that we need to prohibit it saying "We support only strict typescript projects"

Given `IsUnknown` and `IsNever` I would:

* First of all, add them 
* Cover all existing types with test cases with `unknown` and `never`
* Support all existing types with them (probably adjust the logic)

@krzkaczor wdyt?

**Comment by krzkaczor** [comment]
Yes, `InUnknown` and `IsNever` are both useful. I didn't know that these types need special handling 😬 

> Regarding IsAny I have a feeling that we need to prohibit it saying "We support only strict typescript projects"

Can you elaborate on what exactly do you want to do with `IsAny`? I think we can expose it as sometimes it can be useful for ensuring that type inference works correctly but I don't think that we should tweak our types to prevent using `any` or something like this.

**Comment by Beraliv** [comment]
> Yes, `InUnknown` and `IsNever` are both useful. I didn't know that these types need special handling 😬 
> 
> > Regarding IsAny I have a feeling that we need to prohibit it saying "We support only strict typescript projects"
> 
> Can you elaborate on what exactly do you want to do with `IsAny`? I think we can expose it as sometimes it can be useful for ensuring that type inference works correctly but I don't think that we should tweak our types to prevent using `any` or something like this.

At the moment, we allow `any` in our types but maybe it makes sense to prohibit at all, as we move towards strict project

However, I found several `any` in our types and maybe we still can allow some weakness regarding them

We just need to decide what is our way

**Comment by krzkaczor** [comment]
I personally don't have a very strong opinion on this. 

On one hand, I use `any` from time to time and I can clearly see that sometimes it's useful (but only in isolated scopes). 

On the other hand, probably using 90% of types from `ts-essentials` with `any` doesn't make sense and no one does it (at least not on purpose).

**Comment by Beraliv** [comment]
> On one hand, I use `any` from time to time and I can clearly see that sometimes it's useful (but only in isolated scopes).

It depends on who uses ts-essentials

For example, during my development I only use `// @ts-expect-error` comments (which I plan to fix later) as I usually make types working from the beginning

But that's only me, we need to know the opinion of other developers

> On the other hand, probably using 90% of types from `ts-essentials` with `any` doesn't make sense and no one does it (at least not on purpose).

Yeah, exactly

If you want to use `ts-essentials`, probably you already know how to solve problems and won't have `any` that much

You're familiar with its evil "nature" and prefer either disable it with ts comments or make them too general from the beginning and then step by step make them more complicated

But again, that's only my approach, probably others will ask to have intermediate layer with `any`

**Comment by Beraliv** [comment]
So as I understand, first action points are to introduce 2 types: `IsNever` and `IsUnknown`

And then we will decide what to do with `IsAny`

**Comment by krzkaczor** [comment]
> So as I understand, first action point is to introduce 2 types: `IsNever` and `IsUnknown`
> 
> And then we will decide what to do with `IsAny`

Yup, makes sense to me.

**Comment by Beraliv** [comment]
Will plan to release `IsAny` soon – https://github.com/krzkaczor/ts-essentials/pull/264

**Comment by Beraliv** [comment]
Sorry, had problems with CI, release under https://github.com/krzkaczor/ts-essentials/pull/280
