### ISSUE TITLE
CamelCase, SnakeCase etc.

### ISSUE THREAD

**Issue by kitsoRik** [krzkaczor/ts-essentials#254]
Type which allows you to convert objects (or just strings) with snake case-based (`this_is_snake_case`) keys to camelcase-based (`thisIsCamelCase`).

Real example from project:

```typescript
type ThirdPartyApiUserResponse = {
  id: number;
  first_name: string;
  last_name: string;
  middle_name: string;
}

type User = {
  id: number;
  firstName: string;
  lastName: string;
  middleName: string;
}

function adaptee<T extends object>(obj: T) {
  return obj; // with transformed cases
}

```

**Comment by Beraliv** [comment]
@kitsoRik thank you for the suggestion!

First of all, we need to understand what's required here.

Usually, fields from backend are snake case and data in frontend is camel case. So is it only required to switch between them, is it correct?

And the second one is whether it's a common case to transform them

Temporary solution is to implement it yourself for now. I would implement it this way:

```ts
type SplitSnakeCase<T> = T extends `${infer Word}_${infer Tail}` ? [Word, ...SplitSnakeCase<Tail>] : T extends `${infer Word}` ? [Word] : [];

type PascalCapitalizer<T> = T extends [infer Head, ...infer Tail] ? Head extends string ? [Capitalize<Head>, ...PascalCapitalizer<Tail>] : PascalCapitalizer<Tail> : [];

type CamelCapitalizer<T extends string[]> = T extends [infer First, ...infer Tail] ? [First, ...PascalCapitalizer<Tail>] : [];

type Join<T> = T extends [infer Head, ...infer Tail] ? Head extends string ? `${Head}${Join<Tail>}` : Join<Tail> : '';

type SnakeToCamelCase<T> = Join<CamelCapitalizer<SplitSnakeCase<T>>>;
```

Code with tests in the Playground – https://tsplay.dev/wO8j7N

**Comment by kitsoRik** [comment]
> @kitsoRik thank you for the suggestion!
> 
> First of all, we need to understand what's required here.
> 
> Usually, fields from backend are snake case and data in frontend is camel case. So is it only required to switch between them, is it correct?
> 
> And the second one is whether it's a common case to transform them
> 
> Temporary solution is to implement it yourself for now. I would implement it this way:
> 
> ```ts
> type SplitSnakeCase<T> = T extends `${infer Word}_${infer Tail}` ? [Word, ...SplitSnakeCase<Tail>] : T extends `${infer Word}` ? [Word] : [];
> 
> type PascalCapitalizer<T> = T extends [infer Head, ...infer Tail] ? Head extends string ? [Capitalize<Head>, ...PascalCapitalizer<Tail>] : PascalCapitalizer<Tail> : [];
> 
> type CamelCapitalizer<T extends string[]> = T extends [infer First, ...infer Tail] ? [First, ...PascalCapitalizer<Tail>] : [];
> 
> type Join<T> = T extends [infer Head, ...infer Tail] ? Head extends string ? `${Head}${Join<Tail>}` : Join<Tail> : '';
> 
> type SnakeToCamelCase<T> = Join<CamelCapitalizer<SplitSnakeCase<T>>>;
> ```
> 
> Code with tests in the Playground – https://tsplay.dev/wO8j7N

Thanks for response. Anyway. This is not necessarily, we didn't have problem with conversation like that, but it's good way to do it.


> And the second one is whether it's a common case to transform them

I don't agree with you, I've not seen projects written in node.js with snake case.

**Comment by Beraliv** [comment]
> I don't agree with you, I've not seen projects written in node.js with snake case.

I mean it's just an example

Anyway, do you need to switch between those two cases, is it correct?

**Comment by kitsoRik** [comment]
> Anyway, do you need to switch between those two cases, is it correct?

Yeah, we have many integrations with other services which have API with snake case and we always transform it to camel case and I think this type could help us because with this type we can check our results during compilation.

But it is not necessary, just my suggestion

**Comment by Beraliv** [comment]
Btw, it's related to the challenge `Camelize` – https://github.com/type-challenges/type-challenges/blob/master/questions/1383-hard-camelize/README.md

**Comment by Beraliv** [comment]
@kitsoRik ok, I thought it can be still helpful

can you please list all the cases you need to transform one from another? Is it only snake_case and camelCase?

**Comment by kitsoRik** [comment]
It's only from snake case to camel case, I didn't have another situation, but maybe it's better to do it for all popular cases, from one to another.

**Comment by Beraliv** [comment]
> It's only from snake case to camel case, I didn't have another situation, but maybe it's better to do it for all popular cases, from one to another.

I will add `CamelCase` for strings and `CamelCaseProperties` for objects (but it will be applied shallowly)

Do you also apply to do it to the whole object structure or one layer is fine for you?

**Comment by kitsoRik** [comment]
I do it for the whole object (recursively).

**Comment by Beraliv** [comment]
@kitsoRik please have a look at https://github.com/krzkaczor/ts-essentials/pull/271

Does that functionality fit you in your project?

**Comment by kitsoRik** [comment]
@Beraliv Yes, it does. It looks good to me.

**Comment by Beraliv** [comment]
I plan to merge it – https://github.com/krzkaczor/ts-essentials/pull/271 and then release it in https://github.com/krzkaczor/ts-essentials/pull/264

**Comment by Beraliv** [comment]
Sorry, had problems with CI, release under https://github.com/krzkaczor/ts-essentials/pull/280
