### ISSUE TITLE
ts 4.5 broken

### ISSUE THREAD

**Issue by djmisterjon** [krzkaczor/ts-essentials#255]
ReadonlyKeys<> not work in 4.5

**Comment by Beraliv** [comment]
@djmisterjon thank you for the issue!

Let me check it in the evening and I come back to you

**Comment by Beraliv** [comment]
@djmisterjon I used latest dev version of typescript@4.5, and it's still working

Playground – https://tsplay.dev/Wkj9jm

Can you please specify for which case it's not working for you?

In ideal scenario, please provide the type or the interface as an input and the actual / expected output

**Comment by djmisterjon** [comment]
yes , sry i think i used a bad commit version , it work fine now !
