### ISSUE TITLE
Array or not

### ISSUE THREAD

**Issue by kitsoRik** [krzkaczor/ts-essentials#256]
There's a similar example with promise. Like `AsyncOrSync`, good idea to have the same for arrays

```type ArrayOrNot<T> = T | T[];```

**Comment by Beraliv** [comment]
Hey @kitsoRik !

Thank you for the suggestion!

Can you provide the example where it can be useful?

**Comment by kitsoRik** [comment]
> Hey @kitsoRik !
> 
> Thank you for the suggestion!
> 
> Can you provide the example where it can be useful?

Hi. Of course. Sometimes I like to create function which accepts entity of entities (array) and all time I need to write `Entity 
 Entity[]` - and this is simple example, how about more difficult type? Like (Entity | Entiti[] | number | number[] ...). Underhood I just use `castArray` from lodash which transforms one item to array of single element or returns the same array `like (e) => Array.isArray(e) ? e : [e]` and then I work with array. This is good feature for me, I don't know about others but I saw many libs which write function arguments like me.

**Comment by Beraliv** [comment]
> > Hey @kitsoRik !
> > Thank you for the suggestion!
> > Can you provide the example where it can be useful?
> 
> Hi. Of course. Sometimes I like to create function which accepts entity of entities (array) and all time I need to write `Entity Entity[]` - and this is simple example, how about more difficult type? Like (Entity | Entiti[] | number | number[] ...). Underhood I just use `castArray` from lodash which transforms one item to array of single element or returns the same array `like (e) => Array.isArray(e) ? e : [e]` and then I work with array. This is good feature for me, I don't know about others but I saw many libs which write function arguments like me.

Sounds good to me

@krzkaczor wdyt? It's not difficult to implement

**Comment by Beraliv** [comment]
@kitsoRik what do you think if it was `Arrayable` instead of `ArrayOrNot`?

It looks similar to the implementation of [`Promisable` in type-fest](https://github.com/sindresorhus/type-fest/blob/main/source/promisable.d.ts)

**Comment by kitsoRik** [comment]
@Beraliv Hi. It doesn't matter to me.  Yes, in type-fest it is named `Promisable` but in `ts-essentials` it named `AsyncOrSync` so I just suggested a name like this one. Also, I thought about `ArrayOrSingle` - as for me - it sounds better, but anyway, you can implement it with preferred name for you.

**Comment by krzkaczor** [comment]
Seems useful 👍 I would prefer to have consistent naming in this library. I am not saying that `AsyncOrSync` is the perfect name but at least is self-describing. I am not sure if `Promisable` is any better. 

IMO I would go ahead with `ArrayOrSingle` but I am open to any suggestions (maybe we can rename `AsyncOrSync` too?).

**Comment by Beraliv** [comment]
@krzkaczor `AsyncOrSync` sounds self-explanatory
However `Promisable` is not that explicit, so I would say `ArrayOrSingle` LGTM

**Comment by Beraliv** [comment]
Will plan to release it soon – https://github.com/krzkaczor/ts-essentials/pull/264

**Comment by kitsoRik** [comment]
Thanks. Appreciate it.

**Comment by Beraliv** [comment]
Sorry, had problems with CI, release under https://github.com/krzkaczor/ts-essentials/pull/280
