### ISSUE TITLE
How to import "literal"?

### ISSUE THREAD

**Issue by epeli** [krzkaczor/ts-essentials#26]
This does not work

![image](https://user-images.githubusercontent.com/225712/54740943-7aa84780-4bc5-11e9-977b-0d296f697d81.png)

**Comment by krzkaczor** [comment]
Try:

```typescript
import { literal } from "ts-essentials/dist/functions";
```

Thanks for the report. This should be fixed. It's reexported here: https://github.com/krzkaczor/ts-essentials/blob/master/lib/index.ts#L2 but it doesn't work for some weird reason :/

**Comment by yxliang01** [comment]
@krzkaczor Hmm, actually I have had similar problem that I did `import { UnreachableCaseError } from "ts-essentials"` and it didn't work :( . And, indeed I can see that it was reexported... So, I didn't spend much time on investigating nor reporting back then.

**Comment by yxliang01** [comment]
I've finally found the reason... See https://github.com/krzkaczor/ts-essentials/pull/31 .

**Comment by krzkaczor** [comment]
Thanks, @yxliang01! Released as `v2.0.5`
