### ISSUE TITLE
Port the type description in the ts file to README?

### ISSUE THREAD

**Issue by yxliang01** [krzkaczor/ts-essentials#27]
In README, some types are missing the description, only the example. So, wondering shouldn't we port these description to README?

**Comment by krzkaczor** [comment]
@yxliang01 yeah sounds like a good idea. Whole documentation has to be in readme.

**Comment by krzkaczor** [comment]
I added more docs in: https://github.com/krzkaczor/ts-essentials/pull/34 Please reopen if still viable.
