### ISSUE TITLE
[Question] What is the difference between `literal` function and the new Typescript `as const`?

### ISSUE THREAD

**Issue by yxliang01** [krzkaczor/ts-essentials#32]
From what I understand, they are at least very similar. Maybe a clarification can be made to differentiate them. Potentially, the clarification can be added to README.

Thanks

**Comment by krzkaczor** [comment]
Yes, I also understood that it's the same. I will re-read it carefully and update the readme. Thanks for this note.

**Comment by krzkaczor** [comment]
I deprecated `literal` helper in https://github.com/krzkaczor/ts-essentials/pull/34

**Comment by yxliang01** [comment]
@krzkaczor No... I don't think you should do so even they are the same. `as const` was added since Typescript 3.4 while there are many projects not using the latest version yet. I would say the `literal` helper is a backport in that sense. So, I think it's a good idea to add it back.

**Comment by yxliang01** [comment]
@krzkaczor I think saying explicitly as a backport would be more suitable though ? Like suggestions in https://github.com/krzkaczor/ts-essentials/pull/36 .
