### ISSUE TITLE
DeepPartial and Date

### ISSUE THREAD

**Issue by adam-beck** [krzkaczor/ts-essentials#37]
When I have a `Date` inside of an `interface` and attempt to use `DeepPartial<InterfaceWithDate>` I receive errors that I can't assign `Date | DeepPartial<Date>` to `Date`. I'm probably explaining this poorly so I created a demo.

https://stackblitz.com/edit/typescript-rqg3wt

**Comment by krzkaczor** [comment]
I think it's related to symbol usage inside of `Date` fix should be simple — we can filter out symbols or dates. I am busy in the upcoming days, and probably I will be able to fix it on Sunday.

**Comment by krzkaczor** [comment]
Fixed by https://github.com/krzkaczor/ts-essentials/pull/62
