### ISSUE TITLE
Feature JSON type

### ISSUE THREAD

**Issue by Ciantic** [krzkaczor/ts-essentials#38]
I'm not sure if this is even possible, but it would nice to have a JSON type.

Which validates that the value of this type contains just primitives or objects with properties consisted of primitives, arrays or objects (no functions, or Date objects etc.)

I tried to implement it but I keep hitting the recursive type limitation, however you have solved it somehow since DeepReadonly should have same problem.

**Comment by yxliang01** [comment]
@Ciantic Did you mean a type called something like `JSONSerializable` ? This sounds pretty cool :) One thing to mind that we can serialize an object to JSON even when there are functions or non-primitive objects(e.g. `Date` objects) though. As long as there are corresponding `toJSON` method defined and the returning object doesn't contain these JSON-unserializable values.

**Comment by Ciantic** [comment]
I know about `toJSON` but the JSON type I want could be used to validate e.g. a REST api result types that they contain only JSON primitives etc. Maybe it could be named `JSONSerializable`, or simply `JSONType`.

I think if it is possible to do, it could be highly usable and I think a good contribution to TypeScript standard library also.

**Comment by krzkaczor** [comment]
I think I know what you mean. Often I mark json loaded objects as `Object` where in fact it could be a little bit more specific.

Here's discussion + additional comments in TS repo https://github.com/Microsoft/TypeScript/issues/1897

**Comment by Ciantic** [comment]
Okay, looks like the issue is not novel, but somehow I thought it would be possible using similar things as DeepReadonly. I'm closing this because it's probably not possible, since that issue has existed for so long, someone would have found a way already.
