### ISSUE TITLE
DeepReadonly on Tuple type causes type widening to Array

### ISSUE THREAD

**Issue by yxliang01** [krzkaczor/ts-essentials#40]
```typescript
import { DeepReadonly } from "ts-essentials";

const a: [number, string] = [1,'s'];
const b: DeepReadonly<typeof a> = a;
const c = b[1];
```

The variable `c` above will have type `number | string` while the expected type would be `string`. This is caused by the fact that the Tuple type is widened to Array type.

**Comment by krzkaczor** [comment]
Part of `next` branch. Released as `ts-essentials@3.0.0-beta.0`
