### ISSUE TITLE
Proposal: PickRequired / PartialRequired

### ISSUE THREAD

**Issue by IlyaSemenov** [krzkaczor/ts-essentials#45]
I'm using this generic type which I believe is a good fit for ts-essentials:

```ts
export type PickRequired<T, K extends keyof T> = { [P in K]-?: T[P] }
```

**UPDATE 10.06.2019: The suggested implementation is not correct, as it does not say anything about keys *not* in `T`, and essentially repeats `Pick<Required<..>>`. See the discussion below.**

Example usage:

```ts
const user = (await User.query()
	.select("name", "is_admin")
	.where("id", user_id)
	.first()) as PickRequired<User, "name" | "is_admin">
```

Normally, ORM query would return a `Partial<...>` type, because it's not clear which fields will be present in the result set. With `PickRequired`, I can statically attribute that certain fields **will** be present in the result.

I'm not exactly sure about the naming. I considered `PartialRequired` and `PickRequired`, but both bear the unwanted connotations to existing Typescript generics (`Partial` and `Pick`). Pick seemed to be better as it similarly accepts the list of keys.

**UPDATE 10.06.2019: Two more naming variants are `MarkRequired` and `SelectiveRequired`.**

**Comment by krzkaczor** [comment]
Generally, I like this idea — working with ORMs can be a PITA. I am just not sure if we should add such type if it can be easily constructed from already existing ones:

```typescript
type PickRequired <T, K extends keyof T> = Required<Pick<T, K>>
```

If more people find it useful lets definitely add it!

**Comment by IlyaSemenov** [comment]
Required + Pick will have a different meaning (it will *only* leave the picked keys, while the one that I suggested leaves all keys, just marks certain of them as required.)

That said, my example is probably not a very good as Pick + Required is perhaps a better fit for it indeed.

**Comment by krzkaczor** [comment]
Oh, you're right. I think that shows that the name `PickRequired` is not perfect for the first case. 

Anyway, let's wait for feedback from other people that might be interested in using such type.

**Comment by IlyaSemenov** [comment]
Yeah the naming is confusing, I agree. Could be `MarkRequired` perhaps.

**Comment by quezak** [comment]
I'll chip in, since I've done something similar a few days ago :)

> Required + Pick will have a different meaning (it will only leave the picked keys

I believe not -- what you wrote initially, only declares keys from `K` to be present, doesn't say anything about the other keys in T, so it's essentially the same as `Required<Pick<T, K>>`. Example to prove my point:
```
export type PickRequired<T, K extends keyof T> = { [P in K]-?: T[P] };
type UserPicked1 = PickRequired<User, 'id'>;
const test: UserPicked1 = { id: 1, name: 'aaa' };
// ^ error: Object literal may only specify known properties, and 'name' does not exist in type 'PickRequired<User, "id">'`
```

I've used a version of ts-essentials' `Merge`, simplified because the left and right type is the same, so we don't care about what overrides what.
```
export type PickRequired<T, RK extends keyof T> = Exclude<T, RK> & Required<Pick<T, RK>>;
```

The name is indeed causing trouble here -- now, after a few days, I've realized that indeed `PickRequired` _should_ mean _"pick and require some properties", i.e. `Required<Pick<T, RK>>`. Initially I've named this `SelectiveRequired` -- maybe that's better? Or maybe `RequirePicked`?

**Comment by quezak** [comment]
Another note on (1) leaving only required keys vs (2) marking some keys as required: I think both cases are important.

1. In the initial comment by @IlyaSemenov, the example indeed has _only_ `name` and `is_admin` fields selected -- so it should be `Required<Pick<User, 'name' | 'is_admin'>>`

2. In my case, I'm using this type to select a database entity together with some related fields, for example return an `User` instance joined with all his `BankAccount`s (using `typeorm`)
:
```typescript
// User class (excerpt)

export class User {
    @PrimaryGeneratedColumn()
    id!: number
    // ... some other properties

    // this field is optional, since it's a related entity and normally it's not automatically selected
    @OneToMany(_type => BankAccount, acc => acc.user)
    bankAccounts?: BankAccount[];
}

export type UserWithAccounts = PickRequired<User, 'bankAccounts'>;

// ... in UserService:

    async getWithAccounts(id: number): Promise<UserWithAccounts> {
        return this.get(
            { id },
            { relations: ['bankAccounts'] },
        ) as Promise<UserWithAccounts>;
    }
```

**Comment by IlyaSemenov** [comment]
> I believe not -- what you wrote initially, only declares keys from K to be present, doesn't say anything about the other keys in T, so it's essentially the same as `Required<Pick<T, K>>`.

You are right. Not sure what I was thinking. I updated the issue description accordingly.

By the way, in the end (after tossing types this way and another) I don't have the need in any new types, including my original proposal (with incorrect implementation). That said, the imaginary `SelectiveRequired` / `MarkRequired` still probably makes sense.

**Comment by krzkaczor** [comment]
@all-contributors please add @quezak for code, idea

**Comment by krzkaczor** [comment]
Great work guys @quezak @IlyaSemenov I feel like we ended up with another useful type. Possible another extension (closer to original type) would be `SelectRequired` which would pick keys and make them required. This can be also useful while working with ORMs.
