### ISSUE TITLE
Error in types.d.ts for Dictionary

### ISSUE THREAD

**Issue by afreix** [krzkaczor/ts-essentials#46]
I'm getting a build error on Typescript 3.4.5
```
export declare type Dictionary<T, K extends string | number = string> = {
    [key in K]: T;
};
```

Error:
```
Type 'K' is not assignable to type 'string'.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'
```

Seems related to this: https://github.com/microsoft/TypeScript/issues/13398

**Comment by krzkaczor** [comment]
Thanks for the report. I will try to have a look today.

**Comment by krzkaczor** [comment]
@afreix I can't reproduce it on `typescript@3.5.2`

**Comment by glen-84** [comment]
@krzkaczor We're still seeing this on TS 3.5.3.

**Comment by quezak** [comment]
@glen-84 can you provide a minimal failing reproduction?

**Comment by glen-84** [comment]
@quezak,

It looks like it's caused by `"keyofStringsOnly": true` in `tsconfig.json`.

We don't need this option enabled, so I will remove it.

Thanks.
