### ISSUE TITLE
AllContributors 

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/ts-essentials#49]
@all-contributors add @krzkaczor for code

**Comment by krzkaczor** [comment]
@all-contributors please add @krzkaczor for code

**Comment by krzkaczor** [comment]
@all-contributors please add @krzkaczor for business, example, doc

**Comment by krzkaczor** [comment]
@yxliang01, @Andarist, @macbem, @MichaelTontchev, @ThomasdenH, @epeli, @IlyaSemenov you all been added as contributors with all-contributors spec 😉 Thanks once again!

**Comment by yxliang01** [comment]
@krzkaczor :+1:
