### ISSUE TITLE
Extending definition of Primitive?

### ISSUE THREAD

**Issue by lucifer1004** [krzkaczor/ts-essentials#63]
Referring to [type-fest](https://github.com/sindresorhus/type-fest/blob/89f09b3133beb637f3869ba827e1c909acc26c6b/source/basic.d.ts#L7), `bigint`and `symbol` can be added.

Also, it should be noted that

> This can just be `export type Primitive = not object` when the `not` keyword is out.

**Comment by krzkaczor** [comment]
Adding `bigint` and `symbol` definately make sense. 

Negated types (`not`) are gonna help solving https://github.com/krzkaczor/ts-essentials/issues/35 as well

**Comment by krzkaczor** [comment]
@all-contributors please add @lucifer1004 for code, idea

**Comment by krzkaczor** [comment]
Fixed by https://github.com/krzkaczor/ts-essentials/pull/65
