### ISSUE TITLE
DeepRequire on type with function on a property sets that property to {}

### ISSUE THREAD

**Issue by kevinpeno** [krzkaczor/ts-essentials#73]
Below is an example of what I tried to do and the results received. I expect the final notation to be what happens instead.

```ts
type PartialObject = {
  a?: string
  b?: string
  c?: (input: string) => void
}

type RequiredObject = DeepRequired<PartialObject>

// actual type output
type RequiredObject = {
  a: string;
  b: string;
  c: {};
}

// expected type output
type RequiredObject = {
  a: string;
  b: string;
  c: (input: string) => void;
}

**Comment by kevinpeno** [comment]
I'm guessing it is related to the `T extends {}` portion found [here](https://github.com/krzkaczor/ts-essentials/blob/master/lib/types.ts#L28) and that seems necessary to allow for the recursion. So I'm not sure a way to fix it.

**Comment by kevinpeno** [comment]
Okay, I think the issue is resolve in the linked PR. Lemme know any comments.

**Comment by quezak** [comment]
Looks like this is already fixed on the `next` branch, all the `Deep*` types were refactored for such edge cases there. If you're already using TS3.5, or can easily update, you can switch to the `beta` release from npm.
I'm going to approve your PR anyway, so people who can't upgrade to TS3.5 for some reason also can use this fix -- @krzkaczor what do you think?

**Comment by krzkaczor** [comment]
Yeah, it's done on `next`. I think we can merge it for future generations not using TS3.5 😆 I can release it later today.

**Comment by kevinpeno** [comment]
Awesome, thanks for the info. We don't generally use beta versions in prod so this helps a ton :)
