### ISSUE TITLE
DeepReadonly incorrectly converting objects inherited from built-in Array type

### ISSUE THREAD

**Issue by yxliang01** [krzkaczor/ts-essentials#88]
`DeepReadonly` such object will convert it to `DeepReadonlyArray` implicitly incorrectly casting the objects inherited from `Array` to simply `DeepReadonlyArray`.

**Comment by Beraliv** [comment]
@yxliang01 that's fair point

But why do you need to extend `Array` and add properties there? I think that's not a common approach and is hardly needed to be supported

**Comment by yxliang01** [comment]
Consider a very useful method is wanted for an array (say if `pop` isn't defined by default), it might be a good idea to extend the Array class and add the method, instead of declaring a wrapper class.

**Comment by Beraliv** [comment]
> Consider a very useful method is wanted for an array (say if `pop` isn't defined by default), it might be a good idea to extend the Array class and add the method, instead of declaring a wrapper class.

I would use composition over inheritance

**Comment by yxliang01** [comment]
Composition is what I meant by wrapper class. I would prefer inheritance instead. Composition requires you either manually proxy all existing methods of `Array`, or define single proxy method and losing type safety... Why would you prefer composition?

**Comment by Beraliv** [comment]
> Composition is what I meant by wrapper class. I would prefer inheritance instead. Composition requires you either manually proxy all existing methods of `Array`, or define single proxy method and losing type safety... Why would you prefer composition?

For me specifying types yourself instead of using Array types is not a lost, because Array types are not that strict (e.g. includes has its problems)

Also you don't have all inherited methods which can mutate you instance (by accident or on purpose)

Usually composition is more clear (you show what you use and why) even if it's a list of methods instead

But of course, I don't know your case

Btw, why do you extend the whole array, are you sure you need all the methods?

**Comment by Beraliv** [comment]
TypeScript doesn't seem to have something to infer automatically, so it only leads to over-complication with identifying what it is (object by default), e.g.:

```typescript
// we have something confusing here
interface DeepReadonlyArray<T> extends ReadonlyArray<T> {
  foo: 'bar';
}

// we have our type
type A = DeepReadonlyArray<number>;

// we somehow identify that it's `ReadonlyArray` with inferred generic type `number`
type Diff = Omit<A, keyof ReadonlyArray<number>>;

// yes, we inferred diff, but knowing that it's an object
```

That's just one example, but we can confuse it by extending from 2 types, e.g.:

```typescript
interface DeepReadonlyArray<T> extends ReadonlyArray<T>, Function {
  foo: 'bar';
}

type A = DeepReadonlyArray<number>;

type Diff = Omit<A, keyof ReadonlyArray<number>>;
```

That's still possible, but now we need to guess 2 base types which makes the type unusable. The diff is even unreadable:

```bash
type Diff = {
    [Symbol.hasInstance]: (value: any) => boolean;
    foo: 'bar';
    apply: (this: Function, thisArg: any, argArray?: any) => any;
    call: (this: Function, thisArg: any, ...argArray: any[]) => any;
    ... 4 more ...;
    readonly name: string;
}
```

That's still solvable with recursion and the right order of checks

**Comment by Beraliv** [comment]
@krzkaczor I would close it, wdyt?
