### ISSUE TITLE
Align Dictionary<T, K> with adopted standard in other frameworks and SDKs

### ISSUE THREAD

**Issue by series0ne** [krzkaczor/ts-essentials#9]
It seems unusual to see the GTPs in Dictionary defining the Type and then the Key when they are declared in the reverse order:

```
let dict: Dictionary<number, string> = {
    "abc": 123,
    "xyz": 987
// "key" : "value"
};
```

In C#, GTPs are the other way around: `IDictionary<TKey, TValue>`
In Kotlin and Java, GTPs are the other way around: `Map<K, V>`

Suggested solution:

```
type Dictionary<TKey extends string | number = string, TValue = any> = {
    [key in TKey]: TValue;
};

var x: Dictionary<string, string> = {
    "s": "Hello"
}
```

_I'm actually not keen on implicit dictionary type choices, but that's up to you._

**Comment by krzkaczor** [comment]
Please reopen, if further discussion is required.

**Comment by series0ne** [comment]
@krzkaczor Thank you for your prompt response. You've raised some good points here.

**GTP** = Generic Type Parameter; for example `T`, `K` and `V`

I understand that `Dictionary<T, K>` isn't a true dictionary/map in the same sense as C# or Java/Kotlin respectively, however a "plain JS object" _is_ a dictionary _and_ an object at the same time.

I'm alluding to the following gist which is intended to be a joke, poking fun at various programming languages, but it's still quite apt: https://gist.github.com/series0ne/cc7ee637b6e241e130e3b0c6a748cb84

I see your reasoning behind putting `T` before `K` and that's a sound enough rationale for me to not complain about GTP ordering any further :)
