### ISSUE TITLE
Question: overly complex `DeepXXX` type definitions?

### ISSUE THREAD

**Issue by yxliang01** [krzkaczor/ts-essentials#92]
@krzkaczor I'm wondering why there are many conditions that have the same resolved values? Is there any particular reason of doing so?

E.g. https://github.com/krzkaczor/ts-essentials/blob/539307555b206f286147145271443ffe2cddda88/lib/types.ts#L10

The conditions for `Primitive`, `Function` and `Date` can be merged.
I'm suspecting that for a complex object, merging these conditions would have big performance increase?

**Comment by krzkaczor** [comment]
If I am getting you right, you're saying that we can merge these conditions and use union type instead like this:

```typescript
export type DeepPartial<T> = T extends (Primitive | Function | Date)
  ? T
  : T extends Map<infer K, infer V>
  ? DeepPartialMap<K, V>
  : T extends Set<infer U>
  ? DeepPartialSet<U>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;
```


I think that there is no reason why it's written like this, other than standard software engineering debt accumulation and entropy ;) 

Good point 👍 I think merging it makes whole signature smaller and more readable. @quezak thoughts?

**Comment by quezak** [comment]
+1 from me too. I don't think there will be any noticeable performance impact.
