### ISSUE TITLE
DeepWritable does not handle ReadonlyArrays

### ISSUE THREAD

**Issue by a1russell** [krzkaczor/ts-essentials#93]
It doesn't seem that DeepWritable converts ReadonlyArrays. It appears that it used to before #66. Was this removed on purpose for some reason?

**Comment by krzkaczor** [comment]
There is no particular reason 🤷‍♂ I guess its bug.

**Comment by a1russell** [comment]
Nevermind, my particular issue was misunderstanding TypeScript. I had a DeepWritable structure with an array in it, and I was trying to assign a ReadonlyArray to it. Seems I have to cast that ReadonlyArray or clone it.
