### ISSUE TITLE
Simplify type definitions via TS 3.7 recursive type aliases

### ISSUE THREAD

**Issue by lucifer1004** [krzkaczor/ts-essentials#99]
See [here](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html?ref=hvper.com#more-recursive-type-aliases).

By leveraging the recursive type feature introduced in TS 3.7, we no longer need intermediate interfaces to express recursive structures, which can greatly simplify our code base.

Maybe we can open an experimental branch for this, since this would definitely be a breaking change (we will rely on TS 3.7).

**Comment by quezak** [comment]
Yes, definitely!

**Comment by lucifer1004** [comment]
Addressed via #105
